# Generated by Django 4.2.7 on 2023-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_rating_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentdUser',
            new_name='commentedUser',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=250),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
