# Generated by Django 4.2.7 on 2023-11-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_reviewreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreply',
            name='repliedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
